// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Record is the type that is the db schema for ip_details
//
// @uuid VARCHAR(255) NOT NULL,
// @created_at VARCHAR(255  ),
// @updated_at​ VARCHAR(255),
// @response_code​ VARCHAR(255),
// @ip_address​ VARCHAR(255)
type Record struct {
	// uuid for each record
	UUID string `json:"uuid"`
	// time record was created. Unix time.
	CreatedAt int `json:"created_at"`
	// time record was updated. Unix time.
	UpdatedAt int `json:"updated_at"`
	// response_code is NXDOMAIN is response from `godnsbl.Lookup` is nil, else
	// the response_code is the returned string.
	ResponseCode string `json:"response_code"`
	// ip_address is the IP Address used for searching against the Blocklist domain. Used
	// in `godnsbl.Lookup`.
	IPAddress string `json:"ip_address"`
}

// Required Token for running any other queries
// or mutations.
type Token struct {
	// bearer_token: JWT token
	BearerToken string `json:"bearer_token"`
}

// Data type for authenticating user and being granted a token
type UserAuth struct {
	// username
	Username string `json:"username"`
	// password
	Password string `json:"password"`
}
